name: Verify Guides (Small)

on:
  workflow_dispatch: # Allow manual triggering of this workflow.

  push:
    branches: ["master"]

  pull_request:
    branches: ["master"]

jobs:
  small:
    uses: ./.github/workflows/verify-guides.yml
    with:
      test-config-path: "test/_test_config.yml"
