name: Verify Guides (Large)

on:
  workflow_dispatch: # Allow manual triggering of this workflow.

  push:
    paths: ["en/tutorials/"]
    branches: ["master"]

  pull_request:
    paths: ["en/tutorials/"] # Enable before merge!
    branches: ["master"]

jobs:
  large:
    uses: ./.github/workflows/verify-guides.yml
    with:
      test-config-path: "test/_test_config-large.yml"
